# Generated by Django 4.1.7 on 2023-04-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='myuser_ptr',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='language_preferences',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
