# Generated by Django 4.1.7 on 2023-05-31 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_av',
            name='tutor',
        ),
        migrations.AddField(
            model_name='time_av',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='calification',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
