# Generated by Django 4.1.7 on 2023-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
    ]
