# Generated by Django 4.1.7 on 2023-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='payment',
            field=models.CharField(default='0000000000000000', max_length=16, null=True),
        ),
    ]
