# Generated by Django 4.1.7 on 2023-05-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_av',
            name='user',
        ),
        migrations.AddField(
            model_name='time_av',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.tutor'),
            preserve_default=False,
        ),
    ]
