# Generated by Django 4.1.7 on 2023-05-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_customuser_date_joined_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
