# Generated by Django 4.1.7 on 2023-06-03 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_tutor_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pp/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_exp', to=settings.AUTH_USER_MODEL),
        ),
    ]
