# Generated by Django 4.1.7 on 2023-06-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
