# Generated by Django 4.1.7 on 2023-04-19 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'En espera'), (1, 'Aprobado'), (2, 'Rechazado')], default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SesionSolicitada', to='database.session')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='EstudianteSolicitando', to='database.student')),
                ('tutor', models.ManyToManyField(related_name='TutorSolicitado', to='database.tutor')),
            ],
        ),
    ]
