# Generated by Django 4.1.7 on 2023-06-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_tutor_calification_remove_tutor_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='calification',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cost',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
