# Generated by Django 4.1.7 on 2023-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_studentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='language',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='language',
        ),
        migrations.AddField(
            model_name='student',
            name='ccv',
            field=models.IntegerField(default=111, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='ccv',
            field=models.IntegerField(default=222, max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('russian', 'Russian')], max_length=16)),
                ('level', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2')], max_length=20)),
                ('student', models.ManyToManyField(related_name='TutorLanguages', to='database.student')),
                ('tutor', models.ManyToManyField(related_name='TutorLanguages', to='database.tutor')),
            ],
        ),
    ]
