# Generated by Django 4.1.7 on 2023-04-25 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_student_language_remove_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ccv',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='ccv',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
