# Generated by Django 4.1.7 on 2023-05-03 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_customuser_language_language_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
