# Generated by Django 4.1.7 on 2023-04-25 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_student_ccv_alter_tutor_ccv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='student',
        ),
        migrations.RemoveField(
            model_name='language',
            name='tutor',
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ManyToManyField(related_name='Languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
