# Generated by Django 4.1.7 on 2023-06-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_customuser_file_session_calification_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='files/', verbose_name='File'),
        ),
    ]
