# Generated by Django 4.1.7 on 2023-06-04 16:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_customuser_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='file',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
