# Generated by Django 4.1.7 on 2023-06-04 17:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_customuser_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Image'),
        ),
    ]
