# Generated by Django 4.1.7 on 2023-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_language_user_language_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.ManyToManyField(to='database.language'),
        ),
    ]
