# Generated by Django 4.1.7 on 2023-06-04 18:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_customuser_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
