# Generated by Django 4.1.7 on 2023-06-05 02:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_customuser_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
    ]
