# Generated by Django 4.1.7 on 2023-04-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_language_user_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.language'),
            preserve_default=False,
        ),
    ]
