# Generated by Django 4.1.7 on 2023-04-25 15:32

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_remove_customuser_language_customuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ccv',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='ccv',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
