# Generated by Django 4.1.7 on 2023-06-06 22:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_customuser_video_alter_student_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.CharField(default='0000000000000000', max_length=16, null=True),
        ),
    ]
