# Generated by Django 4.1.7 on 2023-06-06 23:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_customuser_video_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='calification',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
